### ISSUE TITLE
Getting Blank screen!

### ISSUE THREAD

**Issue by j3rin** [RepairShopr/react-native-signature-capture#76]
I'm getting blank screen, I'm not able to sign on it. Please help, thanks! 
![img_656ee790461c-1](https://user-images.githubusercontent.com/6828869/29796081-34642ca8-8c1d-11e7-981b-8afaea7f3a6a.jpeg)

**Comment by UnSimpleGeek** [comment]
Seems like a problem with the style of your component. Can you paste your code somewhere, please ?

**Comment by phumaster** [comment]
same issue

**Comment by phumaster** [comment]
<img width="300" alt="screen shot 2017-09-16 at 3 23 47 pm" src="https://user-images.githubusercontent.com/13518558/30510699-18daad74-9af3-11e7-8114-aae9012d59b3.png">

same issue

**Comment by j3rin** [comment]
@phumaster you just have to restart Xcode and your package manager. react linking doesnt work. it works for me now.

**Comment by phumaster** [comment]
Thank you! I think it's not issue for this package. I have react-native-smart-barcode and I uninstall, react-native-signature-capture work!

**Comment by spencewine** [comment]
I had this problem, I corrected it by fixing the styles.

**Comment by Sibren** [comment]
Didn't fix it, unfortunately.
Tested on Android 7, React 0.49.5.

**Comment by spencewine** [comment]
Try putting a border around in styles. If you can't see the component outlined anywhere (mine was in the upper right, then it might be another issue. Try checking the parent container styles as well.

**Comment by Sibren** [comment]
Hi Spencewine,

Thanks for commenting. It had a borderoutline. When using the full code example, the buttons also gave an error, but where functioning.
